// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `server.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Player;

public interface _IMetaServerOperations
{
    MediaInfo[] find(String s, Ice.Current __current);

    MediaInfo[] findByArtist(String s, Ice.Current __current);

    MediaInfo[] findByTitle(String s, Ice.Current __current);

    MediaInfo[] listSongs(Ice.Current __current);

    MusicServerInfo[] listMusicServers(Ice.Current __current);

    StreamToken setupStreaming(MediaInfo media, Ice.Current __current);

    void play(StreamToken token, Ice.Current __current);

    void stop(StreamToken token, Ice.Current __current);
}
