// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `server.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Player;

public interface _IMusicServerOperations
{
    void add(Song s, Ice.Current __current)
        throws Error;

    void remove(String path, Ice.Current __current)
        throws Error;

    Song[] find(String s, Ice.Current __current);

    Song[] findByArtist(String s, Ice.Current __current);

    Song[] findByTitle(String s, Ice.Current __current);

    Song[] listSongs(Ice.Current __current);

    StreamToken setupStreaming(String path, String clientIP, String clientPort, Ice.Current __current);

    void play(StreamToken token, Ice.Current __current);

    void stop(StreamToken token, Ice.Current __current);

    void uploadFile(String path, int offset, byte[] data, Ice.Current __current)
        throws Error;
}
