// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `server.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Player;

public final class IMusicServerPrxHelper extends Ice.ObjectPrxHelperBase implements IMusicServerPrx
{
    private static final String __add_name = "add";

    public void add(Song s)
        throws Error
    {
        add(s, null, false);
    }

    public void add(Song s, java.util.Map<String, String> __ctx)
        throws Error
    {
        add(s, __ctx, true);
    }

    private void add(Song s, java.util.Map<String, String> __ctx, boolean __explicitCtx)
        throws Error
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "add", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __checkTwowayOnly("add");
                    __delBase = __getDelegate(false);
                    _IMusicServerDel __del = (_IMusicServerDel)__delBase;
                    __del.add(s, __ctx, __observer);
                    return;
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_add(Song s)
    {
        return begin_add(s, null, false, null);
    }

    public Ice.AsyncResult begin_add(Song s, java.util.Map<String, String> __ctx)
    {
        return begin_add(s, __ctx, true, null);
    }

    public Ice.AsyncResult begin_add(Song s, Ice.Callback __cb)
    {
        return begin_add(s, null, false, __cb);
    }

    public Ice.AsyncResult begin_add(Song s, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_add(s, __ctx, true, __cb);
    }

    public Ice.AsyncResult begin_add(Song s, Callback_IMusicServer_add __cb)
    {
        return begin_add(s, null, false, __cb);
    }

    public Ice.AsyncResult begin_add(Song s, java.util.Map<String, String> __ctx, Callback_IMusicServer_add __cb)
    {
        return begin_add(s, __ctx, true, __cb);
    }

    private Ice.AsyncResult begin_add(Song s, java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__add_name);
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __add_name, __cb);
        try
        {
            __result.__prepare(__add_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__startWriteParams(Ice.FormatType.DefaultFormat);
            s.__write(__os);
            __result.__endWriteParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public void end_add(Ice.AsyncResult __result)
        throws Error
    {
        Ice.AsyncResult.__check(__result, this, __add_name);
        boolean __ok = __result.__wait();
        try
        {
            if(!__ok)
            {
                try
                {
                    __result.__throwUserException();
                }
                catch(Error __ex)
                {
                    throw __ex;
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            __result.__readEmptyParams();
        }
        catch(Ice.LocalException ex)
        {
            Ice.Instrumentation.InvocationObserver __obsv = __result.__getObserver();
            if(__obsv != null)
            {
                __obsv.failed(ex.ice_name());
            }
            throw ex;
        }
    }

    private static final String __find_name = "find";

    public Song[] find(String s)
    {
        return find(s, null, false);
    }

    public Song[] find(String s, java.util.Map<String, String> __ctx)
    {
        return find(s, __ctx, true);
    }

    private Song[] find(String s, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "find", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __checkTwowayOnly("find");
                    __delBase = __getDelegate(false);
                    _IMusicServerDel __del = (_IMusicServerDel)__delBase;
                    return __del.find(s, __ctx, __observer);
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_find(String s)
    {
        return begin_find(s, null, false, null);
    }

    public Ice.AsyncResult begin_find(String s, java.util.Map<String, String> __ctx)
    {
        return begin_find(s, __ctx, true, null);
    }

    public Ice.AsyncResult begin_find(String s, Ice.Callback __cb)
    {
        return begin_find(s, null, false, __cb);
    }

    public Ice.AsyncResult begin_find(String s, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_find(s, __ctx, true, __cb);
    }

    public Ice.AsyncResult begin_find(String s, Callback_IMusicServer_find __cb)
    {
        return begin_find(s, null, false, __cb);
    }

    public Ice.AsyncResult begin_find(String s, java.util.Map<String, String> __ctx, Callback_IMusicServer_find __cb)
    {
        return begin_find(s, __ctx, true, __cb);
    }

    private Ice.AsyncResult begin_find(String s, java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__find_name);
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __find_name, __cb);
        try
        {
            __result.__prepare(__find_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeString(s);
            __result.__endWriteParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public Song[] end_find(Ice.AsyncResult __result)
    {
        Ice.AsyncResult.__check(__result, this, __find_name);
        boolean __ok = __result.__wait();
        try
        {
            if(!__ok)
            {
                try
                {
                    __result.__throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.__startReadParams();
            Song[] __ret;
            __ret = SongSeqHelper.read(__is);
            __result.__endReadParams();
            return __ret;
        }
        catch(Ice.LocalException ex)
        {
            Ice.Instrumentation.InvocationObserver __obsv = __result.__getObserver();
            if(__obsv != null)
            {
                __obsv.failed(ex.ice_name());
            }
            throw ex;
        }
    }

    private static final String __findByArtist_name = "findByArtist";

    public Song[] findByArtist(String s)
    {
        return findByArtist(s, null, false);
    }

    public Song[] findByArtist(String s, java.util.Map<String, String> __ctx)
    {
        return findByArtist(s, __ctx, true);
    }

    private Song[] findByArtist(String s, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "findByArtist", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __checkTwowayOnly("findByArtist");
                    __delBase = __getDelegate(false);
                    _IMusicServerDel __del = (_IMusicServerDel)__delBase;
                    return __del.findByArtist(s, __ctx, __observer);
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_findByArtist(String s)
    {
        return begin_findByArtist(s, null, false, null);
    }

    public Ice.AsyncResult begin_findByArtist(String s, java.util.Map<String, String> __ctx)
    {
        return begin_findByArtist(s, __ctx, true, null);
    }

    public Ice.AsyncResult begin_findByArtist(String s, Ice.Callback __cb)
    {
        return begin_findByArtist(s, null, false, __cb);
    }

    public Ice.AsyncResult begin_findByArtist(String s, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_findByArtist(s, __ctx, true, __cb);
    }

    public Ice.AsyncResult begin_findByArtist(String s, Callback_IMusicServer_findByArtist __cb)
    {
        return begin_findByArtist(s, null, false, __cb);
    }

    public Ice.AsyncResult begin_findByArtist(String s, java.util.Map<String, String> __ctx, Callback_IMusicServer_findByArtist __cb)
    {
        return begin_findByArtist(s, __ctx, true, __cb);
    }

    private Ice.AsyncResult begin_findByArtist(String s, java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__findByArtist_name);
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __findByArtist_name, __cb);
        try
        {
            __result.__prepare(__findByArtist_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeString(s);
            __result.__endWriteParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public Song[] end_findByArtist(Ice.AsyncResult __result)
    {
        Ice.AsyncResult.__check(__result, this, __findByArtist_name);
        boolean __ok = __result.__wait();
        try
        {
            if(!__ok)
            {
                try
                {
                    __result.__throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.__startReadParams();
            Song[] __ret;
            __ret = SongSeqHelper.read(__is);
            __result.__endReadParams();
            return __ret;
        }
        catch(Ice.LocalException ex)
        {
            Ice.Instrumentation.InvocationObserver __obsv = __result.__getObserver();
            if(__obsv != null)
            {
                __obsv.failed(ex.ice_name());
            }
            throw ex;
        }
    }

    private static final String __findByTitle_name = "findByTitle";

    public Song[] findByTitle(String s)
    {
        return findByTitle(s, null, false);
    }

    public Song[] findByTitle(String s, java.util.Map<String, String> __ctx)
    {
        return findByTitle(s, __ctx, true);
    }

    private Song[] findByTitle(String s, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "findByTitle", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __checkTwowayOnly("findByTitle");
                    __delBase = __getDelegate(false);
                    _IMusicServerDel __del = (_IMusicServerDel)__delBase;
                    return __del.findByTitle(s, __ctx, __observer);
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_findByTitle(String s)
    {
        return begin_findByTitle(s, null, false, null);
    }

    public Ice.AsyncResult begin_findByTitle(String s, java.util.Map<String, String> __ctx)
    {
        return begin_findByTitle(s, __ctx, true, null);
    }

    public Ice.AsyncResult begin_findByTitle(String s, Ice.Callback __cb)
    {
        return begin_findByTitle(s, null, false, __cb);
    }

    public Ice.AsyncResult begin_findByTitle(String s, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_findByTitle(s, __ctx, true, __cb);
    }

    public Ice.AsyncResult begin_findByTitle(String s, Callback_IMusicServer_findByTitle __cb)
    {
        return begin_findByTitle(s, null, false, __cb);
    }

    public Ice.AsyncResult begin_findByTitle(String s, java.util.Map<String, String> __ctx, Callback_IMusicServer_findByTitle __cb)
    {
        return begin_findByTitle(s, __ctx, true, __cb);
    }

    private Ice.AsyncResult begin_findByTitle(String s, java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__findByTitle_name);
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __findByTitle_name, __cb);
        try
        {
            __result.__prepare(__findByTitle_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeString(s);
            __result.__endWriteParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public Song[] end_findByTitle(Ice.AsyncResult __result)
    {
        Ice.AsyncResult.__check(__result, this, __findByTitle_name);
        boolean __ok = __result.__wait();
        try
        {
            if(!__ok)
            {
                try
                {
                    __result.__throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.__startReadParams();
            Song[] __ret;
            __ret = SongSeqHelper.read(__is);
            __result.__endReadParams();
            return __ret;
        }
        catch(Ice.LocalException ex)
        {
            Ice.Instrumentation.InvocationObserver __obsv = __result.__getObserver();
            if(__obsv != null)
            {
                __obsv.failed(ex.ice_name());
            }
            throw ex;
        }
    }

    private static final String __listSongs_name = "listSongs";

    public Song[] listSongs()
    {
        return listSongs(null, false);
    }

    public Song[] listSongs(java.util.Map<String, String> __ctx)
    {
        return listSongs(__ctx, true);
    }

    private Song[] listSongs(java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "listSongs", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __checkTwowayOnly("listSongs");
                    __delBase = __getDelegate(false);
                    _IMusicServerDel __del = (_IMusicServerDel)__delBase;
                    return __del.listSongs(__ctx, __observer);
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_listSongs()
    {
        return begin_listSongs(null, false, null);
    }

    public Ice.AsyncResult begin_listSongs(java.util.Map<String, String> __ctx)
    {
        return begin_listSongs(__ctx, true, null);
    }

    public Ice.AsyncResult begin_listSongs(Ice.Callback __cb)
    {
        return begin_listSongs(null, false, __cb);
    }

    public Ice.AsyncResult begin_listSongs(java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_listSongs(__ctx, true, __cb);
    }

    public Ice.AsyncResult begin_listSongs(Callback_IMusicServer_listSongs __cb)
    {
        return begin_listSongs(null, false, __cb);
    }

    public Ice.AsyncResult begin_listSongs(java.util.Map<String, String> __ctx, Callback_IMusicServer_listSongs __cb)
    {
        return begin_listSongs(__ctx, true, __cb);
    }

    private Ice.AsyncResult begin_listSongs(java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__listSongs_name);
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __listSongs_name, __cb);
        try
        {
            __result.__prepare(__listSongs_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            __result.__writeEmptyParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public Song[] end_listSongs(Ice.AsyncResult __result)
    {
        Ice.AsyncResult.__check(__result, this, __listSongs_name);
        boolean __ok = __result.__wait();
        try
        {
            if(!__ok)
            {
                try
                {
                    __result.__throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.__startReadParams();
            Song[] __ret;
            __ret = SongSeqHelper.read(__is);
            __result.__endReadParams();
            return __ret;
        }
        catch(Ice.LocalException ex)
        {
            Ice.Instrumentation.InvocationObserver __obsv = __result.__getObserver();
            if(__obsv != null)
            {
                __obsv.failed(ex.ice_name());
            }
            throw ex;
        }
    }

    private static final String __play_name = "play";

    public void play(StreamToken token)
    {
        play(token, null, false);
    }

    public void play(StreamToken token, java.util.Map<String, String> __ctx)
    {
        play(token, __ctx, true);
    }

    private void play(StreamToken token, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "play", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __delBase = __getDelegate(false);
                    _IMusicServerDel __del = (_IMusicServerDel)__delBase;
                    __del.play(token, __ctx, __observer);
                    return;
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_play(StreamToken token)
    {
        return begin_play(token, null, false, null);
    }

    public Ice.AsyncResult begin_play(StreamToken token, java.util.Map<String, String> __ctx)
    {
        return begin_play(token, __ctx, true, null);
    }

    public Ice.AsyncResult begin_play(StreamToken token, Ice.Callback __cb)
    {
        return begin_play(token, null, false, __cb);
    }

    public Ice.AsyncResult begin_play(StreamToken token, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_play(token, __ctx, true, __cb);
    }

    public Ice.AsyncResult begin_play(StreamToken token, Callback_IMusicServer_play __cb)
    {
        return begin_play(token, null, false, __cb);
    }

    public Ice.AsyncResult begin_play(StreamToken token, java.util.Map<String, String> __ctx, Callback_IMusicServer_play __cb)
    {
        return begin_play(token, __ctx, true, __cb);
    }

    private Ice.AsyncResult begin_play(StreamToken token, java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __play_name, __cb);
        try
        {
            __result.__prepare(__play_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__startWriteParams(Ice.FormatType.DefaultFormat);
            token.__write(__os);
            __result.__endWriteParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public void end_play(Ice.AsyncResult __result)
    {
        __end(__result, __play_name);
    }

    private static final String __remove_name = "remove";

    public void remove(String path)
        throws Error
    {
        remove(path, null, false);
    }

    public void remove(String path, java.util.Map<String, String> __ctx)
        throws Error
    {
        remove(path, __ctx, true);
    }

    private void remove(String path, java.util.Map<String, String> __ctx, boolean __explicitCtx)
        throws Error
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "remove", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __checkTwowayOnly("remove");
                    __delBase = __getDelegate(false);
                    _IMusicServerDel __del = (_IMusicServerDel)__delBase;
                    __del.remove(path, __ctx, __observer);
                    return;
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_remove(String path)
    {
        return begin_remove(path, null, false, null);
    }

    public Ice.AsyncResult begin_remove(String path, java.util.Map<String, String> __ctx)
    {
        return begin_remove(path, __ctx, true, null);
    }

    public Ice.AsyncResult begin_remove(String path, Ice.Callback __cb)
    {
        return begin_remove(path, null, false, __cb);
    }

    public Ice.AsyncResult begin_remove(String path, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_remove(path, __ctx, true, __cb);
    }

    public Ice.AsyncResult begin_remove(String path, Callback_IMusicServer_remove __cb)
    {
        return begin_remove(path, null, false, __cb);
    }

    public Ice.AsyncResult begin_remove(String path, java.util.Map<String, String> __ctx, Callback_IMusicServer_remove __cb)
    {
        return begin_remove(path, __ctx, true, __cb);
    }

    private Ice.AsyncResult begin_remove(String path, java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__remove_name);
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __remove_name, __cb);
        try
        {
            __result.__prepare(__remove_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeString(path);
            __result.__endWriteParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public void end_remove(Ice.AsyncResult __result)
        throws Error
    {
        Ice.AsyncResult.__check(__result, this, __remove_name);
        boolean __ok = __result.__wait();
        try
        {
            if(!__ok)
            {
                try
                {
                    __result.__throwUserException();
                }
                catch(Error __ex)
                {
                    throw __ex;
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            __result.__readEmptyParams();
        }
        catch(Ice.LocalException ex)
        {
            Ice.Instrumentation.InvocationObserver __obsv = __result.__getObserver();
            if(__obsv != null)
            {
                __obsv.failed(ex.ice_name());
            }
            throw ex;
        }
    }

    private static final String __setupStreaming_name = "setupStreaming";

    public StreamToken setupStreaming(String path, String clientIP, String clientPort)
    {
        return setupStreaming(path, clientIP, clientPort, null, false);
    }

    public StreamToken setupStreaming(String path, String clientIP, String clientPort, java.util.Map<String, String> __ctx)
    {
        return setupStreaming(path, clientIP, clientPort, __ctx, true);
    }

    private StreamToken setupStreaming(String path, String clientIP, String clientPort, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "setupStreaming", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __checkTwowayOnly("setupStreaming");
                    __delBase = __getDelegate(false);
                    _IMusicServerDel __del = (_IMusicServerDel)__delBase;
                    return __del.setupStreaming(path, clientIP, clientPort, __ctx, __observer);
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_setupStreaming(String path, String clientIP, String clientPort)
    {
        return begin_setupStreaming(path, clientIP, clientPort, null, false, null);
    }

    public Ice.AsyncResult begin_setupStreaming(String path, String clientIP, String clientPort, java.util.Map<String, String> __ctx)
    {
        return begin_setupStreaming(path, clientIP, clientPort, __ctx, true, null);
    }

    public Ice.AsyncResult begin_setupStreaming(String path, String clientIP, String clientPort, Ice.Callback __cb)
    {
        return begin_setupStreaming(path, clientIP, clientPort, null, false, __cb);
    }

    public Ice.AsyncResult begin_setupStreaming(String path, String clientIP, String clientPort, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_setupStreaming(path, clientIP, clientPort, __ctx, true, __cb);
    }

    public Ice.AsyncResult begin_setupStreaming(String path, String clientIP, String clientPort, Callback_IMusicServer_setupStreaming __cb)
    {
        return begin_setupStreaming(path, clientIP, clientPort, null, false, __cb);
    }

    public Ice.AsyncResult begin_setupStreaming(String path, String clientIP, String clientPort, java.util.Map<String, String> __ctx, Callback_IMusicServer_setupStreaming __cb)
    {
        return begin_setupStreaming(path, clientIP, clientPort, __ctx, true, __cb);
    }

    private Ice.AsyncResult begin_setupStreaming(String path, String clientIP, String clientPort, java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__setupStreaming_name);
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __setupStreaming_name, __cb);
        try
        {
            __result.__prepare(__setupStreaming_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeString(path);
            __os.writeString(clientIP);
            __os.writeString(clientPort);
            __result.__endWriteParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public StreamToken end_setupStreaming(Ice.AsyncResult __result)
    {
        Ice.AsyncResult.__check(__result, this, __setupStreaming_name);
        boolean __ok = __result.__wait();
        try
        {
            if(!__ok)
            {
                try
                {
                    __result.__throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.__startReadParams();
            StreamToken __ret;
            __ret = new StreamToken();
            __ret.__read(__is);
            __result.__endReadParams();
            return __ret;
        }
        catch(Ice.LocalException ex)
        {
            Ice.Instrumentation.InvocationObserver __obsv = __result.__getObserver();
            if(__obsv != null)
            {
                __obsv.failed(ex.ice_name());
            }
            throw ex;
        }
    }

    private static final String __stop_name = "stop";

    public void stop(StreamToken token)
    {
        stop(token, null, false);
    }

    public void stop(StreamToken token, java.util.Map<String, String> __ctx)
    {
        stop(token, __ctx, true);
    }

    private void stop(StreamToken token, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "stop", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __delBase = __getDelegate(false);
                    _IMusicServerDel __del = (_IMusicServerDel)__delBase;
                    __del.stop(token, __ctx, __observer);
                    return;
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_stop(StreamToken token)
    {
        return begin_stop(token, null, false, null);
    }

    public Ice.AsyncResult begin_stop(StreamToken token, java.util.Map<String, String> __ctx)
    {
        return begin_stop(token, __ctx, true, null);
    }

    public Ice.AsyncResult begin_stop(StreamToken token, Ice.Callback __cb)
    {
        return begin_stop(token, null, false, __cb);
    }

    public Ice.AsyncResult begin_stop(StreamToken token, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_stop(token, __ctx, true, __cb);
    }

    public Ice.AsyncResult begin_stop(StreamToken token, Callback_IMusicServer_stop __cb)
    {
        return begin_stop(token, null, false, __cb);
    }

    public Ice.AsyncResult begin_stop(StreamToken token, java.util.Map<String, String> __ctx, Callback_IMusicServer_stop __cb)
    {
        return begin_stop(token, __ctx, true, __cb);
    }

    private Ice.AsyncResult begin_stop(StreamToken token, java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __stop_name, __cb);
        try
        {
            __result.__prepare(__stop_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__startWriteParams(Ice.FormatType.DefaultFormat);
            token.__write(__os);
            __result.__endWriteParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public void end_stop(Ice.AsyncResult __result)
    {
        __end(__result, __stop_name);
    }

    public static IMusicServerPrx checkedCast(Ice.ObjectPrx __obj)
    {
        IMusicServerPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof IMusicServerPrx)
            {
                __d = (IMusicServerPrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId()))
                {
                    IMusicServerPrxHelper __h = new IMusicServerPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static IMusicServerPrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        IMusicServerPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof IMusicServerPrx)
            {
                __d = (IMusicServerPrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId(), __ctx))
                {
                    IMusicServerPrxHelper __h = new IMusicServerPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static IMusicServerPrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        IMusicServerPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId()))
                {
                    IMusicServerPrxHelper __h = new IMusicServerPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static IMusicServerPrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        IMusicServerPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId(), __ctx))
                {
                    IMusicServerPrxHelper __h = new IMusicServerPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static IMusicServerPrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        IMusicServerPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof IMusicServerPrx)
            {
                __d = (IMusicServerPrx)__obj;
            }
            else
            {
                IMusicServerPrxHelper __h = new IMusicServerPrxHelper();
                __h.__copyFrom(__obj);
                __d = __h;
            }
        }
        return __d;
    }

    public static IMusicServerPrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        IMusicServerPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            IMusicServerPrxHelper __h = new IMusicServerPrxHelper();
            __h.__copyFrom(__bb);
            __d = __h;
        }
        return __d;
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::Player::IMusicServer"
    };

    public static String ice_staticId()
    {
        return __ids[1];
    }

    protected Ice._ObjectDelM __createDelegateM()
    {
        return new _IMusicServerDelM();
    }

    protected Ice._ObjectDelD __createDelegateD()
    {
        return new _IMusicServerDelD();
    }

    public static void __write(IceInternal.BasicStream __os, IMusicServerPrx v)
    {
        __os.writeProxy(v);
    }

    public static IMusicServerPrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            IMusicServerPrxHelper result = new IMusicServerPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
