// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `server.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Player;

public final class IMusicServerMonitorPrxHelper extends Ice.ObjectPrxHelperBase implements IMusicServerMonitorPrx
{
    private static final String __musicServerDown_name = "musicServerDown";

    public void musicServerDown(String hostname, String listeningPort, String streamingPort)
    {
        musicServerDown(hostname, listeningPort, streamingPort, null, false);
    }

    public void musicServerDown(String hostname, String listeningPort, String streamingPort, java.util.Map<String, String> __ctx)
    {
        musicServerDown(hostname, listeningPort, streamingPort, __ctx, true);
    }

    private void musicServerDown(String hostname, String listeningPort, String streamingPort, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "musicServerDown", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __delBase = __getDelegate(false);
                    _IMusicServerMonitorDel __del = (_IMusicServerMonitorDel)__delBase;
                    __del.musicServerDown(hostname, listeningPort, streamingPort, __ctx, __observer);
                    return;
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_musicServerDown(String hostname, String listeningPort, String streamingPort)
    {
        return begin_musicServerDown(hostname, listeningPort, streamingPort, null, false, null);
    }

    public Ice.AsyncResult begin_musicServerDown(String hostname, String listeningPort, String streamingPort, java.util.Map<String, String> __ctx)
    {
        return begin_musicServerDown(hostname, listeningPort, streamingPort, __ctx, true, null);
    }

    public Ice.AsyncResult begin_musicServerDown(String hostname, String listeningPort, String streamingPort, Ice.Callback __cb)
    {
        return begin_musicServerDown(hostname, listeningPort, streamingPort, null, false, __cb);
    }

    public Ice.AsyncResult begin_musicServerDown(String hostname, String listeningPort, String streamingPort, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_musicServerDown(hostname, listeningPort, streamingPort, __ctx, true, __cb);
    }

    public Ice.AsyncResult begin_musicServerDown(String hostname, String listeningPort, String streamingPort, Callback_IMusicServerMonitor_musicServerDown __cb)
    {
        return begin_musicServerDown(hostname, listeningPort, streamingPort, null, false, __cb);
    }

    public Ice.AsyncResult begin_musicServerDown(String hostname, String listeningPort, String streamingPort, java.util.Map<String, String> __ctx, Callback_IMusicServerMonitor_musicServerDown __cb)
    {
        return begin_musicServerDown(hostname, listeningPort, streamingPort, __ctx, true, __cb);
    }

    private Ice.AsyncResult begin_musicServerDown(String hostname, String listeningPort, String streamingPort, java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __musicServerDown_name, __cb);
        try
        {
            __result.__prepare(__musicServerDown_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeString(hostname);
            __os.writeString(listeningPort);
            __os.writeString(streamingPort);
            __result.__endWriteParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public void end_musicServerDown(Ice.AsyncResult __result)
    {
        __end(__result, __musicServerDown_name);
    }

    private static final String __newMusicServer_name = "newMusicServer";

    public void newMusicServer(String hostname, String listeningPort, String streamingPort)
    {
        newMusicServer(hostname, listeningPort, streamingPort, null, false);
    }

    public void newMusicServer(String hostname, String listeningPort, String streamingPort, java.util.Map<String, String> __ctx)
    {
        newMusicServer(hostname, listeningPort, streamingPort, __ctx, true);
    }

    private void newMusicServer(String hostname, String listeningPort, String streamingPort, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "newMusicServer", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __delBase = __getDelegate(false);
                    _IMusicServerMonitorDel __del = (_IMusicServerMonitorDel)__delBase;
                    __del.newMusicServer(hostname, listeningPort, streamingPort, __ctx, __observer);
                    return;
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_newMusicServer(String hostname, String listeningPort, String streamingPort)
    {
        return begin_newMusicServer(hostname, listeningPort, streamingPort, null, false, null);
    }

    public Ice.AsyncResult begin_newMusicServer(String hostname, String listeningPort, String streamingPort, java.util.Map<String, String> __ctx)
    {
        return begin_newMusicServer(hostname, listeningPort, streamingPort, __ctx, true, null);
    }

    public Ice.AsyncResult begin_newMusicServer(String hostname, String listeningPort, String streamingPort, Ice.Callback __cb)
    {
        return begin_newMusicServer(hostname, listeningPort, streamingPort, null, false, __cb);
    }

    public Ice.AsyncResult begin_newMusicServer(String hostname, String listeningPort, String streamingPort, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_newMusicServer(hostname, listeningPort, streamingPort, __ctx, true, __cb);
    }

    public Ice.AsyncResult begin_newMusicServer(String hostname, String listeningPort, String streamingPort, Callback_IMusicServerMonitor_newMusicServer __cb)
    {
        return begin_newMusicServer(hostname, listeningPort, streamingPort, null, false, __cb);
    }

    public Ice.AsyncResult begin_newMusicServer(String hostname, String listeningPort, String streamingPort, java.util.Map<String, String> __ctx, Callback_IMusicServerMonitor_newMusicServer __cb)
    {
        return begin_newMusicServer(hostname, listeningPort, streamingPort, __ctx, true, __cb);
    }

    private Ice.AsyncResult begin_newMusicServer(String hostname, String listeningPort, String streamingPort, java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __newMusicServer_name, __cb);
        try
        {
            __result.__prepare(__newMusicServer_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeString(hostname);
            __os.writeString(listeningPort);
            __os.writeString(streamingPort);
            __result.__endWriteParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public void end_newMusicServer(Ice.AsyncResult __result)
    {
        __end(__result, __newMusicServer_name);
    }

    public static IMusicServerMonitorPrx checkedCast(Ice.ObjectPrx __obj)
    {
        IMusicServerMonitorPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof IMusicServerMonitorPrx)
            {
                __d = (IMusicServerMonitorPrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId()))
                {
                    IMusicServerMonitorPrxHelper __h = new IMusicServerMonitorPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static IMusicServerMonitorPrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        IMusicServerMonitorPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof IMusicServerMonitorPrx)
            {
                __d = (IMusicServerMonitorPrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId(), __ctx))
                {
                    IMusicServerMonitorPrxHelper __h = new IMusicServerMonitorPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static IMusicServerMonitorPrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        IMusicServerMonitorPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId()))
                {
                    IMusicServerMonitorPrxHelper __h = new IMusicServerMonitorPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static IMusicServerMonitorPrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        IMusicServerMonitorPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId(), __ctx))
                {
                    IMusicServerMonitorPrxHelper __h = new IMusicServerMonitorPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static IMusicServerMonitorPrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        IMusicServerMonitorPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof IMusicServerMonitorPrx)
            {
                __d = (IMusicServerMonitorPrx)__obj;
            }
            else
            {
                IMusicServerMonitorPrxHelper __h = new IMusicServerMonitorPrxHelper();
                __h.__copyFrom(__obj);
                __d = __h;
            }
        }
        return __d;
    }

    public static IMusicServerMonitorPrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        IMusicServerMonitorPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            IMusicServerMonitorPrxHelper __h = new IMusicServerMonitorPrxHelper();
            __h.__copyFrom(__bb);
            __d = __h;
        }
        return __d;
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::Player::IMusicServerMonitor"
    };

    public static String ice_staticId()
    {
        return __ids[1];
    }

    protected Ice._ObjectDelM __createDelegateM()
    {
        return new _IMusicServerMonitorDelM();
    }

    protected Ice._ObjectDelD __createDelegateD()
    {
        return new _IMusicServerMonitorDelD();
    }

    public static void __write(IceInternal.BasicStream __os, IMusicServerMonitorPrx v)
    {
        __os.writeProxy(v);
    }

    public static IMusicServerMonitorPrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            IMusicServerMonitorPrxHelper result = new IMusicServerMonitorPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
