// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `server.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Player;

public final class IMusicServerMonitorHolder extends Ice.ObjectHolderBase<IMusicServerMonitor>
{
    public
    IMusicServerMonitorHolder()
    {
    }

    public
    IMusicServerMonitorHolder(IMusicServerMonitor value)
    {
        this.value = value;
    }

    public void
    patch(Ice.Object v)
    {
        if(v == null || v instanceof IMusicServerMonitor)
        {
            value = (IMusicServerMonitor)v;
        }
        else
        {
            IceInternal.Ex.throwUOE(type(), v);
        }
    }

    public String
    type()
    {
        return _IMusicServerMonitorDisp.ice_staticId();
    }
}
