// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `server.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Player;

public interface ISongMonitorPrx extends Ice.ObjectPrx
{
    public void newSong(Song s);

    public void newSong(Song s, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_newSong(Song s);

    public Ice.AsyncResult begin_newSong(Song s, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_newSong(Song s, Ice.Callback __cb);

    public Ice.AsyncResult begin_newSong(Song s, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_newSong(Song s, Callback_ISongMonitor_newSong __cb);

    public Ice.AsyncResult begin_newSong(Song s, java.util.Map<String, String> __ctx, Callback_ISongMonitor_newSong __cb);

    public void end_newSong(Ice.AsyncResult __result);
}
